[tasks.setup-kotlin_language_server]
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

download_tmp_path='/tmp/kotlin-language-server'
download_filename='server'
mkdir "$download_tmp_path" && cd "$download_tmp_path"

curl -sL https://api.github.com/repos/fwcd/kotlin-language-server/releases/latest  \
  | jq  -r '.assets[].browser_download_url' \
  | grep "${download_filename}.zip" \
  | xargs curl -fsLJO

unzip "${download_filename}.zip"

lsp_dir="$HOME/lsp/kotlin"
mkdir -p "$lsp_dir"
mv "${download_tmp_path}/${download_filename}" "$lsp_dir"

rm -rf "$DOWNLOAD_BINARY_TMP_PATH"
'''
]

