[tasks.install_cli]
category = "tools"
description = "Install CLI tools"
run_task = { name = [
  "install_exa",
  "install_fd",
  "install_fzf",
  "install_git-delta",
  "install_jq",
  "install_ripgrep",
  "install_zoxide",
  "install_cargo-watch",
  "install_cargo-update",
  "install_slack_cli",
] }

[tasks.update_cli]
category = "tools"
description = "Update CLI tools"
run_task = { name = [
  "update_slack_cli",
] }

# exa
[tasks.install_exa]
private = true
script = [
'''
#!/usr/bin/env bash

cargo install exa
'''
]

# fd
[tasks.install_fd]
private = true
script = [
'''
#!/usr/bin/env bash

cargo install fd-find 
'''
]

# fzf
[tasks.install_fzf.mac]
private = true
script = [
'''
#!/usr/bin/env bash

brew install fzf
yes | $(brew --prefix)/opt/fzf/install
'''
]

[tasks.install_fzf.linux]
private = true
script = [
'''
#!/usr/bin/env bash

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
yes | ~/.fzf/install
'''
]

# git-delta
[tasks.install_git-delta]
private = true
script = [
'''
#!/usr/bin/env bash

cargo install git-delta
'''
]

# jq
[tasks.install_jq.mac]
private = true
script = [
'''
#!/usr/bin/env bash

brew install jq 
'''
]

[tasks.install_jq.linux]
private = true
script = [
'''
#!/usr/bin/env bash

sudo apt install -y jq
'''
]

# ripgrep
[tasks.install_ripgrep]
private = true
script = [
'''
#!/usr/bin/env bash

cargo install ripgrep
'''
]

# zoxide
[tasks.install_zoxide]
private = true
script = [
'''
#!/usr/bin/env bash

cargo install zoxide
echo 'eval "$(zoxide init bash)"' >> ~/.profile
'''
]

[tasks.install_cargo-watch]
private = true
script = [
'''
#!/usr/bin/env bash

cargo install cargo-watch
'''
]

[tasks.install_cargo-update]
private = true
script = [
'''
#!/usr/bin/env bash

cargo install cargo-update
'''
]

[tasks.install_slack_cli]
private = true
script = [
'''
#!/usr/bin/env bash

curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash
'''
]

[tasks.update_slack_cli]
private = true
alias = "install_slack_cli"
