[tasks.install_cli]
category = "tools"
description = "Install CLI tools"
run_task = { name = [
  "install_fzf",
  "install_cargo-watch",
  "install_cargo-update",
  "install_slack_cli",
  "instal_aws_cli",
] }

[tasks.update_cli]
category = "tools"
description = "Update CLI tools"
run_task = { name = [
  "update_slack_cli",
  "update_aws_cli",
] }

# fzf
[tasks.install_fzf.mac]
private = true
script = [
'''
#!/usr/bin/env bash

brew install fzf
yes | $(brew --prefix)/opt/fzf/install
'''
]

[tasks.install_fzf.linux]
private = true
script = [
'''
#!/usr/bin/env bash

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
yes | ~/.fzf/install
'''
]

[tasks.install_cargo-watch]
private = true
script = [
'''
#!/usr/bin/env bash

cargo install cargo-watch
'''
]

[tasks.install_cargo-update]
private = true
script = [
'''
#!/usr/bin/env bash

cargo install cargo-update
'''
]

[tasks.install_slack_cli]
private = true
script = [
'''
#!/usr/bin/env bash

curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash
'''
]

[tasks.update_slack_cli]
private = true
alias = "install_slack_cli"

[tasks.instal_aws_cli]
private = true
script = ['''
#!/usr/bin/env bash

FILE_NAME='AWSCLIV2.pkg'

cd /tmp || exit
curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "$FILE_NAME"
sudo installer -pkg "./${FILE_NAME}" -target /
rm "$FILE_NAME"

aws --version
''']

[tasks.update_aws_cli]
private = true
alias = "instal_aws_cli"
