[tasks.install_cli]
run_task = [
  { name = [
    "install_bat",
    "install_dapr",
    "install_direnv",
    "install_exa",
    "install_fd",
    "install_fzf",
    "install_ghq",
    "install_git-delta",
    "install_jq",
    "install_ripgrep",
    "install_zoxide",
  ] },
]

[tasks.update_cli]
run_task = [{ name = ["update_dapr", "update_ghq"] }]

# bat
[tasks.install_bat]
script = [
'''
#!/usr/bin/env bash

cargo install --locked bat
'''
]
dependencies = ["dependencies_bat"]

[tasks.dependencies_bat.linux]
script = [
'''
#!/usr/bin/env bash

sudo apt install -y libclang-dev
'''
]

# dapr
[tasks.install_dapr.mac]
script = [
'''
#!/usr/bin/env bash

curl -fsSL https://raw.githubusercontent.com/dapr/cli/master/install/install.sh | /bin/bash
'''
]

[tasks.install_dapr.linux]
script = [
'''
#!/usr/bin/env bash

wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
'''
]

[tasks.update_dapr.mac]
run_task = [{ name = ["install_dapr"] }]

[tasks.update_dapr.linux]
run_task = [{ name = ["install_dapr"] }]

# direnv
[tasks.install_direnv.mac]
script = [
'''
#!/usr/bin/env bash

brew install direnv
'''
]

[tasks.install_direnv.linux]
script = [
'''
#!/usr/bin/env bash

sudo apt install -y direnv
echo 'export EDITOR=nvim' >> ~/.profile
echo 'eval "$(direnv hook bash)"' >> ~/.profile
'''
]

# exa
[tasks.install_exa]
script = [
'''
#!/usr/bin/env bash

cargo install exa
'''
]

# fd
[tasks.install_fd]
script = [
'''
#!/usr/bin/env bash

cargo install fd-find 
'''
]

# fzf
[tasks.install_fzf.mac]
script = [
'''
#!/usr/bin/env bash

brew install fzf
yes | $(brew --prefix)/opt/fzf/install
'''
]

[tasks.install_fzf.linux]
script = [
'''
#!/usr/bin/env bash

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
yes | ~/.fzf/install
'''
]

# ghq
[tasks.install_ghq.mac]
script = [
'''
#!/usr/bin/env bash

brew install ghq
'''
]

[tasks.install_ghq.linux]
script = [
'''
#!/usr/bin/env bash

go get github.com/x-motemen/ghq
'''
]

[tasks.update_ghq.linux]
script = [
'''
#!/usr/bin/env bash

go get -u github.com/x-motemen/ghq
'''
]

# git-delta
[tasks.install_git-delta]
script = [
'''
#!/usr/bin/env bash

cargo install git-delta
'''
]

# jq
[tasks.install_jq.mac]
script = [
'''
#!/usr/bin/env bash

brew install jq 
'''
]

[tasks.install_jq.linux]
script = [
'''
#!/usr/bin/env bash

sudo apt install -y jq
'''
]

# ripgrep
[tasks.install_ripgrep]
script = [
'''
#!/usr/bin/env bash

cargo install ripgrep
'''
]

# zoxide
[tasks.install_zoxide]
script = [
'''
#!/usr/bin/env bash

cargo install zoxide
echo 'eval "$(zoxide init bash)"' >> ~/.profile
'''
]
