vim.keymap.set("n", "j", "gj", { noremap = true })
vim.keymap.set("n", "k", "gk", { noremap = true })
vim.keymap.set("n", "<C-j>", "<C-w>j")
vim.keymap.set("n", "<C-k>", "<C-w>k")
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("n", "<C-n>", ":noh<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<Space>w", ":w!<CR>", { silent = true })
vim.keymap.set("n", ";", ":", { noremap = true })
vim.keymap.set("i", "jj", "<ESC>", { noremap = true, silent = true })
vim.keymap.set("i", "jjw", "<ESC>:w!<CR>", { noremap = true, silent = true })
vim.keymap.set("i", "jjq", "<ESC>:wq!<CR>", { noremap = true, silent = true })
