[tasks.install_go]
description = "Install Golang"
category = "INSTALL_LANGUAGE"
script = [
'''
#!/usr/bin/env bash

if test -z "$GO_VERSION"; then
  echo "GO_VERSION must be set"
  exit 1
fi

if !(type asdf > /dev/null 2>&1); then
  source ~/.profile
fi

asdf install golang "$GO_VERSION"
asdf global golang "$GO_VERSION"

echo 'export GOPATH="$HOME/go"' >> ~/.profile
echo 'export PATH="$GOPATH/bin:$PATH"' >> ~/.profile
'''
]
dependencies = ["asdf_go_plugin"]

[tasks.asdf_go_plugin]
description = "Install asdf plugin for Golang"
category = "INSTALL_ASDF_PLUGIN"
script = [
'''
#!/usr/bin/env bash

if !(type asdf > /dev/null 2>&1); then
  source ~/.profile
fi

asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
'''
]
