[tasks.install_go]
category = "languages"
description = "Install Go"
dependencies = ["asdf_go_plugin"]
script = [
'''
#!/usr/bin/env bash

if !(type asdf > /dev/null 2>&1); then
  source $HOME/.asdf/asdf.sh
fi

asdf install golang latest
asdf global golang latest

echo 'export GOPATH="$HOME/go"' >> ~/.profile
echo 'export PATH="$GOPATH/bin:$PATH"' >> ~/.profile
'''
]

[tasks.asdf_go_plugin]
private = true
script = [
'''
#!/usr/bin/env bash

if !(type asdf > /dev/null 2>&1); then
  source $HOME/.asdf/asdf.sh
fi

asdf plugin add golang https://github.com/kennyp/asdf-golang.git
'''
]
