[tasks.go]
dependencies = ["add_go_plugin", "install_go"]

[tasks.asdf_go]
script = [
'''
#!/usr/bin/env bash

if !(type asdf > /dev/null 2>&1); then
    source ~/.profile
fi

asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
'''
]

[tasks.install_go]
script = [
'''
#!/usr/bin/env bash

if !(type asdf > /dev/null 2>&1); then
    source ~/.profile
fi

asdf install "$GO_VERSION"
asdf global "$GO_VERSION"

echo 'export GOPATH="$HOME/go"' >> ~/.profile
echo 'export PATH="$GOPATH/bin:$PATH"' >> ~/.profile
'''
]
