[tasks.install_go]
description = "Install Golang"
category = "INSTALL_LANGUAGE"
condition = { env_set = ["GO_VERION"], fail_message = "$GO_VERSION must be set" }
script = [
'''
#!/usr/bin/env bash
set -eux

if !(type asdf > /dev/null 2>&1); then
    source ~/.profile
fi

asdf install golang "$GO_VERSION"
asdf global golang "$GO_VERSION"

echo 'export GOPATH="$HOME/go"' >> ~/.profile
echo 'export PATH="$GOPATH/bin:$PATH"' >> ~/.profile
'''
]
dependencies = ["asdf_go_plugin"]

[tasks.asdf_go_plugin]
description = "Install asdf plugin for Golang"
category = "INSTALL_ASDF_PLUGIN"
script = [
'''
#!/usr/bin/env bash
set -eux

if !(type asdf > /dev/null 2>&1); then
    source ~/.profile
fi

asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
'''
]
