[tasks.setup_python]
category = "languages"
description = "Setup python"
run_task = { name = ["install_python"] }

[tasks.install_python]
private = true
dependencies = ["dependencies_python", "asdf_python_plugin"]
script = [
'''
#!/usr/bin/env bash

if !(type asdf > /dev/null 2>&1); then
  source $HOME/.asdf/asdf.sh
fi

asdf install python latest
asdf set --home python latest
'''
]

[tasks.dependencies_python.mac]
private = true
script = [
'''
#!/usr/bin/env bash

brew install readline xz
'''
]

[tasks.dependencies_python.linux]
private = true
script = [
'''
#!/usr/bin/env bash

sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
  libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
  xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git
'''
]

[tasks.asdf_python_plugin]
private = true
script = [
'''
#!/usr/bin/env bash

if !(type asdf > /dev/null 2>&1); then
  source $HOME/.asdf/asdf.sh
fi

asdf plugin add python
'''
]
