[tasks.setup_python]
description = "Install Python and dependency management tool"
category = "SETUP_LANGUAGE"
run_task = [{ name = ["install_python", "pyflow"] }]

[tasks.install_python]
description = "Install Python"
category = "INSTALL_LANGUAGE"
script = [
'''
#!/usr/bin/env bash

if test -z "$PYTHON_VERSION"; then
  echo "PYTHON_VERSION must be set"
  exit 1
fi

if !(type asdf > /dev/null 2>&1); then
  source ~/.profile
fi

asdf install python "$PYTHON_VERSION"
asdf install python 2.7.18
asdf global python "$PYTHON_VERSION" 2.7.18
'''
]
dependencies = ["dependencies_python", "asdf_python_plugin"]

[tasks.dependencies_python.mac]
description = "Install Python dependencies"
category = "INSTALL_DEPENDENCIES"
script = [
'''
#!/usr/bin/env bash

brew install readline xz
'''
]

[tasks.dependencies_python.linux]
description = "Install Python dependencies"
category = "INSTALL_DEPENDENCIES"
script = [
'''
#!/usr/bin/env bash

sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
  libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
  xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
'''
]

[tasks.asdf_python_plugin]
description = "Install asdf plugin for Python"
category = "INSTALL_ASDF_PLUGIN"
script = [
'''
#!/usr/bin/env bash

if !(type asdf > /dev/null 2>&1); then
  source ~/.profile
fi

asdf plugin-add python
'''
]

[tasks.pyflow]
description = "Install pyflow for manage python dependencies"
category = "INSTALL_DEPENDENCY_MANAGEMENT_TOOL"
script = [
'''
#!/usr/bin/env bash

cargo install pyflow
'''
]

[tasks.update_pip_version]
description = "Update pip version"
category = "UPDATE"
script = [
'''
#!/usr/bin/env bash

python2 -m pip install --user --upgrade pip
python3 -m pip install --user --upgrade pip
'''
]
