[tasks.setup_python]
run_task = [{ name = ["install_python", "install_package_manager"] }]

[tasks.install_python]
private = true
dependencies = ["dependencies_python", "asdf_python_plugin"]
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

if !(type asdf > /dev/null 2>&1); then
  source ~/.profile
fi

asdf install python latest
asdf install python 2.7.18
asdf global python latest 2.7.18
'''
]

[tasks.dependencies_python.mac]
private = true
script = [
'''
#!/usr/bin/env bash

brew install readline xz
'''
]

[tasks.dependencies_python.linux]
private = true
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
  libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
  xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
'''
]

[tasks.asdf_python_plugin]
private = true
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

if !(type asdf > /dev/null 2>&1); then
  source ~/.profile
fi

asdf plugin add python
'''
]

[tasks.install_package_manager]
private = true
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
'''
]

[tasks.update_python]
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

asdf install python latest
asdf global python latest 2.7.18
'''
]

[tasks.update_pip_version]
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

python2 -m pip install --user --upgrade pip
python3 -m pip install --user --upgrade pip
'''
]
