[tasks.setup_aqua]
description = "setup asdf"
run_task = { name = ["install_aqua", "install_aqua_packages"]}

[tasks.install_aqua]
private = true
description = "install aqua"
script = ['''
#!/usr/bin/env bash
set -eux -o pipefail

cd /tmp || exit
curl -sSfL -O https://raw.githubusercontent.com/aquaproj/aqua-installer/v2.1.1/aqua-installer
echo "c2af02bdd15da6794f9c98db40332c804224930212f553a805425441f8331665  aqua-installer" | sha256sum -c
chmod +x aqua-installer
./aqua-installer
''']

[tasks.install_aqua_packages]
private = true
description = "install aqua packages"
script = ['''
#!/usr/bin/env bash
set -eux -o pipefail

aqua i
''']
