[tasks.setup_docker.mac]
category = "Docker"
description = "Install Docker"
dependencies = ["setup_lima", "install_docker", "install_docker-compose", "install_docker-buildx"]
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

docker context create "lima-docker" \
  --docker host="unix://$HOME/.lima/docker/sock/docker.sock"
docker context create "lima-docker-amd" \
  --docker host="unix://$HOME/.lima/docker-amd/sock/docker.sock"
'''
]

[tasks.update_docker_cli_plugins.mac]
category = "Docker"
description = "Update docker CLI plugins"
run_task = [{ name = ["update_docker-compose", "update_docker-buildx"] }]

[tasks.setup_lima.mac]
private = true
run_task = [{ name = ["install_lima", "upgrade_filedescriptor", "start_lima_default", "start_lima_amd"] }]

[tasks.install_lima.mac]
private = true
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

brew install lima
'''
]

[tasks.start_lima_default.mac]
private = true
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

limactl start --name="docker" "./lima/docker.yaml"
limactl stop docker
'''
]

[tasks.start_lima_amd.mac]
private = true
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

limactl start --name="docker-amd" "./lima/docker-amd.yaml"
limactl stop docker-amd
'''
]

[tasks.upgrade_filedescriptor.mac]
private = true
condition = { profiles = ["production"] }
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

sudo ln -snfv ~/dotfiles/lima/limit.maxfiles.plist /Library/LaunchDaemons/
sudo chown root /Library/LaunchDaemons/limit.maxfiles.plist
sudo launchctl load -w /Library/LaunchDaemons/limit.maxfiles.plist
'''
]

[tasks.install_docker.mac]
private = true
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

brew install docker
'''
]

[tasks.install_docker-compose.mac]
private = true
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

DOWNLOAD_BINARY_TMP_PATH='/tmp/docker-compose'

curl -sL --retry 3 https://api.github.com/repos/docker/compose/releases/latest \
  | jq -r '.assets[].browser_download_url' \
  | grep -E "docker-compose-darwin-aarch64" \
  | xargs curl -Lfo "$DOWNLOAD_BINARY_TMP_PATH"

sudo chmod +x "$DOWNLOAD_BINARY_TMP_PATH"

mkdir -p ~/.docker/cli-plugins
cp "$DOWNLOAD_BINARY_TMP_PATH" $HOME/.docker/cli-plugins

rm -rf "$DOWNLOAD_BINARY_TMP_PATH"
'''
]

[tasks.update_docker-compose.mac]
private = true
run_task = [{ name = ["install_docker-compose"] }]

[tasks.install_docker-buildx.mac]
private = true
script = [
'''
#!/usr/bin/env bash
set -eux -o pipefail

DOWNLOAD_BINARY_TMP_PATH='/tmp/docker-buildx'

curl -sL --retry 3 https://api.github.com/repos/docker/buildx/releases/latest \
  | jq -r '.assets[].browser_download_url' \
  | grep -E "buildx-v[0-9]+.[0-9]+.[0-9]+\.darwin-arm64" \
  | xargs curl -Lfo "$DOWNLOAD_BINARY_TMP_PATH"

sudo chmod +x "$DOWNLOAD_BINARY_TMP_PATH"

mkdir -p $HOME/.docker/cli-plugins
cp "$DOWNLOAD_BINARY_TMP_PATH" $HOME/.docker/cli-plugins

rm "$DOWNLOAD_BINARY_TMP_PATH"
'''
]

[tasks.update_docker-buildx.mac]
private = true
run_task = [{ name = ["install_docker-buildx"] }]
