[tasks.setup_fish]
category = "fish"
description = "Setup fish shell"
run_task = { name = ["install_fish", "link_fish"] }

[tasks.install_fish.mac]
private = true
script = [
'''
#!/usr/bin/env bash

brew install fish
'''
]

[tasks.install_fish.linux]
private = true
script = [
'''
#!/usr/bin/env bash

sudo apt-add-repository ppa:fish-shell/release-3
sudo apt update -y
sudo apt install -y fish
'''
]

[tasks.link_fish]
private = true
script = [
'''
#!/usr/bin/env bash

mkdir -p $HOME/.config/fish/functions
mkdir -p $HOME/.config/fish/completions

ln -snfv $HOME/dotfiles/.config/fish/config.fish $HOME/.config/fish
ln -snfv $HOME/dotfiles/.config/fish/functions/* $HOME/.config/fish/functions
ln -snfv $HOME/dotfiles/.config/fish/completions/* $HOME/.config/fish/completions
'''
]
