[tasks.setup_neovim]
category = "Neovim"
description = "Setup Neovim"
run_task = { name = [
  "install_neovim",
  "link_neovim",
] }

[tasks.install_neovim.mac]
private = true
script = [
'''
#!/usr/bin/env bash

brew install neovim
'''
]

[tasks.install_neovim.linux]
private = true
script = [
'''
#!/usr/bin/env bash

sudo add-apt-repository -y ppa:neovim-ppa/stable
sudo apt update -y
sudo apt install -y neovim
'''
]

[tasks.link_neovim]
private = true
script = [
'''
#!/usr/bin/env bash

ln -snfv ~/dotfiles/nvim ~/.config
'''
]
