[tasks.setup_neovim]
dependencies = [
  "install_neovim",
  "install_dein",
  "link_neovim",
  "install_neovim_provider",
]

[tasks.install_neovim.mac]
script = [
'''
#!/usr/bin/env bash

brew install neovim
'''
]

[tasks.install_neovim.linux]
script = [
'''
#!/usr/bin/env bash

sudo add-apt-repository -y ppa:neovim-ppa/stable
sudo apt update -y
sudo apt install -y neovim
'''
]

[tasks.install_dein]
script = [
'''
#!/usr/bin/env bash

curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > ~/installer.sh
sh ~/installer.sh ~/.cache/dein
rm ~/installer.sh
'''
]

[tasks.link_neovim]
script = [
'''
#!/usr/bin/env bash

ln -snfv ~/dotfiles/.config/nvim ~/.config
'''
]

[tasks.install_neovim_provider]
script = [
'''
#!/usr/bin/env bash

if type python >/dev/null 2>&1; then
  python2 -m pip install --user --upgrade pynvim
  python3 -m pip install --user --upgrade pynvim
fi

if type node >/dev/null 2>&1; then
  npm install -g neovim
fi
'''
]

[tasks.update_neovim_provider]
script = [
'''
#!/usr/bin/env bash

if type python >/dev/null 2>&1; then
  python2 -m pip install --user --upgrade pynvim
  python3 -m pip install --user --upgrade pynvim
fi

if type node >/dev/null 2>&1; then
  npm install -g neovim
fi
'''
]

[tasks.update_neovim_plugins]
script = [
'''
#!/usr/bin/env bash

nvim +"call dein#update()" +qall
'''
]
