[tasks.starship]
dependencies = ["install_starship", "link_starship"]

[tasks.install_starship]
script = [
'''
#!/usr/bin/env bash

cargo install starship
'''
]

[tasks.link_starship]
script = [
'''
#!/usr/bin/env bash

ln -snfv ~/dotfiles/.config/starship.toml ~/.config/
'''
]
