[tasks.setup_starship]
category = "tools"
description = "Setup starship"
run_task = { name = ["install_starship", "link_starship"] }

[tasks.install_starship]
private = true
script = [
'''
#!/usr/bin/env bash

sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
'''
]

[tasks.link_starship]
private = true
script = [
'''
#!/usr/bin/env bash

ln -snfv ~/dotfiles/.config/starship.toml ~/.config/
'''
]

[tasks.update_starship]
category = "tools"
description = "Update starship"
alias = "install_starship"
