[tasks.setup_starship]
dependencies = ["install_starship", "link_starship"]

[tasks.install_starship]
script = [
'''
#!/usr/bin/env bash

sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
'''
]

[tasks.link_starship]
script = [
'''
#!/usr/bin/env bash

ln -snfv ~/dotfiles/.config/starship.toml ~/.config/
'''
]

[tasks.update_starship]
script = [
'''
#!/usr/bin/env bash

sh -c "$(curl -fsSL https://starship.rs/install.sh)"
'''
]
