[tasks.setup_starship]
dependencies = ["install_starship", "link_starship"]

[tasks.install_starship.mac]
script = [
'''
#!/usr/bin/env bash

brew install starship
'''
]


[tasks.install_starship.linux]
script = [
'''
#!/usr/bin/env bash

curl -fsSL https://starship.rs/install.sh | bash
'''
]

[tasks.link_starship]
script = [
'''
#!/usr/bin/env bash

ln -snfv ~/dotfiles/.config/starship.toml ~/.config/
'''
]
