[tasks.setup_starship]
category = "SETUP"
dependencies = ["install_starship", "link_starship"]

[tasks.install_starship]
category = "INSTALL"
script = [
'''
#!/usr/bin/env bash

cargo install starship
'''
]

[tasks.link_starship]
category = "LINK"
script = [
'''
#!/usr/bin/env bash

ln -snfv ~/dotfiles/.config/starship.toml ~/.config/
'''
]
