model = "gpt-5.6-luna"
model_reasoning_effort = "max"
[projects."/Users/takahiko-yamashita/ghq/github.com/takahiko-yamashita/gourmet-service"]
trust_level = "trusted"

[projects."/Users/takahiko-yamashita/dotfiles"]
trust_level = "trusted"

[projects."/Users/takahiko-yamashita/Downloads"]
trust_level = "trusted"

[projects."/Users/takahiko-yamashita/ghq/github.com/RettyInc/retty-monorepo-terraform"]
trust_level = "trusted"

[projects."/Users/takahiko-yamashita/ghq/github.com/pyama2000/agent-skills"]
trust_level = "trusted"

[projects."/Users/takahiko-yamashita"]
trust_level = "trusted"

[projects."/Users/takahiko-yamashita/workspace/retty/fy27-infra-cost-estimate"]
trust_level = "trusted"

[features]
hooks = true

[hooks.state]

[hooks.state."/Users/takahiko-yamashita/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:061c82430ee36a3de59e5fe605289a9c059cbb81884226f24e2b65425ffb53d5"

[tui]
theme = "gruvbox-dark"
status_line = ["model-with-reasoning", "current-dir", "project-name", "git-branch"]
status_line_use_colors = true

[marketplaces.claude-plugins-official]
last_updated = "2026-08-18T05:28:52Z"
last_revision = "7458b5e539d2b1d4bff72a303250cab2f4744ef0"
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[marketplaces.mymarketplace]
last_updated = "2026-08-18T07:07:38Z"
last_revision = "d874446aeee5b7ecc75770a0fd78de9af49757fc"
source_type = "git"
source = "git@github.com:pyama2000/agent-skills.git"

[plugins."superpowers@claude-plugins-official"]
enabled = true

[plugins."mattpocock-skills@claude-plugins-official"]
enabled = true

[plugins."myplugin@mymarketplace"]
enabled = true

[mcp_servers.awslabs_aws-knowledge-mcp-server]
url = "https://knowledge-mcp.global.api.aws"

[mcp_servers.awslabs_aws-documentation-mcp-server]
command = "uvx"
args = ["awslabs.aws-documentation-mcp-server@latest"]

[mcp_servers.aws-mcp]
command = "uvx"
args = ["mcp-proxy-for-aws@1.6.2", "https://aws-mcp.us-east-1.api.aws/mcp", "--skip-auth", "--metadata", "INSTALL_SOURCE=agent-toolkit"]
