name: Setup a development environment for macOS and Ubuntu
on: [push]
jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11, ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    # Install and setup
    - name: Setup fish 
      if: always()
      run: cargo make --makefile script/task.toml setup_fish
    - name: Install asdf 
      if: always()
      run: cargo make --makefile script/task.toml install_asdf
    - name: Setup Node
      if: always()
      run: cargo make --makefile script/task.toml install_node -e NODE_VERSION="$NODE_VERSION"
      env:
        NODE_VERSION: 12.16.3
    - name: Update npm
      if: always()
      run: cargo make --makefile script/task.toml update_npm_version
    - name: (DEBUG) Update npm@7.6.0
      if: always()
      run: cargo make --makefile script/task.toml update_npm_version -e NPM_VERSION="7.6.0"
    - name: Cleanup
      if: always()
      run: cargo make --makefile script/task.toml cleanup
