name: check
on:
  pull_request:
    branches:
      - main
    types:
      - "synchronize"
      - "opened"
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint workflow files
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.17.1
          args: --check .
  status-check:
    runs-on: ubuntu-latest
    needs:
      - actionlint
      - stylua
    if: always()
    steps:
      - if: (needs.actionlint.result == 'failure' || needs.stylua.result == 'failure')
        run: exit 1
      - run: exit 0
