name: Setup a development environment for macOS and Ubuntu
on:
  push:
    paths:
      - ".github/workflows/action.yml"
      - "script/*/***"
jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11, ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    # Install and setup
    - name: Run setup.sh
      run: ./script/install.sh
    - name: Install Git
      if: always()
      run: cargo make --makefile script/task.toml install_git -e GIT_NAME="$GIT_NAME" -e GIT_EMAIL="$GIT_EMAIL"
      env:
        GIT_NAME: pyama2000
        GIT_EMAIL: example@example.com
    - name: Clone dotfiles
      if: always()
      run: cargo make --makefile script/task.toml setup_dotfiles
    - name: Create git config link
      if: always()
      run: cargo make --makefile script/task.toml link_git
    - name: Create local git config file
      if: always()
      run: cargo make --makefile script/task.toml gen_git_local -e GIT_NAME="$GIT_NAME" -e GIT_EMAIL="$GIT_EMAIL"
    - name: Setup alacritty 
      if: always()
      run: cargo make --makefile script/task.toml setup_alacritty
    - name: Setup tmux
      if: always()
      run: cargo make --makefile script/task.toml setup_tmux
    - name: Setup fish 
      if: always()
      run: cargo make --makefile script/task.toml setup_fish
    - name: Setup starship
      if: always()
      run: cargo make --makefile script/task.toml setup_starship
    - name: Install asdf 
      if: always()
      run: cargo make --makefile script/task.toml install_asdf
    - name: Setup languages
      if: always()
      run: cargo make --makefile script/task.toml setup_languages -e PYTHON_VERSION="$PYTHON_VERSION" -e GO_VERSION="$GO_VERSION" -e NODE_VERSION="$NODE_VERSION"
      env:
        PYTHON_VERSION: 3.9.0
        GO_VERSION: 1.14.2
        NODE_VERSION: 12.16.3
    - name: Install tools
      if: always()
      run: cargo make --makefile script/task.toml install_tools
    - name: Setup neovim
      if: always()
      run: cargo make --makefile script/task.toml setup_neovim
    - name: Setup vim 
      if: always()
      run: cargo make --makefile script/task.toml link_vim 
    - name: Create bash config link
      if: always()
      run: cargo make --makefile script/task.toml link_bash
    # Update Task
    - name: Update Neovim provider
      if: always()
      run: cargo make --makefile script/task.toml update_neovim_provider
    - name: Update language
      if: always()
      run: cargo make --makefile script/task.toml update_languages -e NPM_UPDATE_VERSION="$NPM_UPDATE_VERSION"
      env:
        NPM_UPDATE_VERSION: "7.6.0"
    - name: Update Alacritty 
      if: always()
      run: cargo make --makefile script/task.toml update_alacritty
    - name: Update tools
      if: always()
      run: cargo make --makefile script/task.toml update_tools
    - name: Cleanup
      if: always()
      run: cargo make --makefile script/task.toml cleanup
