name: Setup a development environment for macOS and Ubuntu
on:
  push:
    paths:
      - ".github/workflows/**"
      - "script/**"
jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: Run setup.sh
      run: ./script/install.sh
    - name: Run setup task
      env:
        GIT_NAME: pyama2000
        GIT_EMAIL: example@example.com
        PYTHON_VERSION: 3.10.2
        GO_VERSION: 1.17.7
        NODE_VERSION: 16.14.0
      run: |
        cargo make --makefile script/task.toml setup \
          -e GIT_NAME="$GIT_NAME" \
          -e GIT_EMAIL="$GIT_EMAIL" \
          -e PYTHON_VERSION="$PYTHON_VERSION" \
          -e GO_VERSION="$GO_VERSION" \
          -e NODE_VERSION="$NODE_VERSION"
    - name: Run update task
      env:
        NPM_UPDATE_VERSION: "7.6.0"
      run: cargo make --makefile script/task.toml update -e NPM_UPDATE_VERSION="$NPM_UPDATE_VERSION"
