name: check
on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened
      - ready_for_review
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    if: >-
      github.event.pull_request.draft == false &&
      github.event.label.name != 'dependencies'
    steps:
      - name: Enable auto-merge
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
        run: gh pr merge --auto --merge "$PR_URL"
  pre-install-and-update:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.export.outputs.diff }}
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            .github/workflows/**
            script/**
      - name: Export outputs
        id: export
        run: echo "diff=${{ env.GIT_DIFF }}" >> "$GITHUB_OUTPUT"
  install-and-update:
    needs:
      - pre-install-and-update
    if: >-
      contains(needs.pre-install-and-update.outputs.diff, '.github/workflows/') ||
      contains(needs.pre-install-and-update.outputs.diff, 'script/')
    uses: ./.github/workflows/install-and-update.yaml
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint workflow files
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -ignore 'label ".+" is unknown'
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.17.1
          args: --check .
  status-check:
    runs-on: ubuntu-latest
    needs:
      - install-and-update
      - actionlint
      - stylua
    if: always()
    steps:
      - name: Failure
        if: >-
          needs.install-and-update.result == 'failure' ||
          needs.install-and-update.result == 'cancelled' ||
          needs.actionlint.result == 'failure' ||
          needs.actionlint.result == 'cancelled' ||
          needs.stylua.result == 'failure' ||
          needs.stylua.result == 'cancelled'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
        run: |
          gh pr merge --disable-auto "$PR_URL"
          exit 1
      - name: Success
        run: exit 0
