name: check
on:
  pull_request:
    branches:
      - main
    types:
      - "synchronize"
      - "opened"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            # .github/workflows/**
            script/**
      - name: Run setup.sh
        if: contains(env.GIT_DIFF, '.github/workflows/') || contains(env.GIT_DIFF, 'script/')
        run: ./script/install.sh
      - name: Run setup task
        if: contains(env.GIT_DIFF, '.github/workflows/') || contains(env.GIT_DIFF, 'script/')
        env:
          GIT_NAME: pyama2000
          GIT_EMAIL: example@example.com
        run: |
          cargo make --makefile script/task.toml setup \
            -e GIT_NAME="$GIT_NAME" \
            -e GIT_EMAIL="$GIT_EMAIL"
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint workflow files
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -ignore 'label ".+" is unknown'
  stylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.17.1
          args: --check .
  status-check:
    runs-on: ubuntu-latest
    needs:
      - install
      - actionlint
      - stylua
    if: always()
    steps:
      - if: (needs.install.result == 'failure' || needs.actionlint.result == 'failure' || needs.stylua.result == 'failure')
        run: exit 1
      - run: exit 0
