name: install-and-update
on:
  pull_request:
    branches:
      - main
    types:
      - "opened"
      - "synchronize"
    paths:
      - "script/**"
jobs:
  install-and-update:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Run setup.sh
        run: ./script/install.sh
      - name: Run setup task
        env:
          GIT_NAME: pyama2000
          GIT_EMAIL: example@example.com
          PYTHON_VERSION: 3.10.2
          GO_VERSION: 1.17.0
          NODE_VERSION: 18.16.0
        run: |
          cargo make --makefile script/task.toml setup \
            -e GIT_NAME="$GIT_NAME" \
            -e GIT_EMAIL="$GIT_EMAIL" \
            -e PYTHON_VERSION="$PYTHON_VERSION" \
            -e GO_VERSION="$GO_VERSION" \
            -e NODE_VERSION="$NODE_VERSION"
