name: install-and-update
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build-nix:
    runs-on: ${{ matrix.os }}
    if: >-
      !contains(github.event.pull_request.labels.*.name, 'skip ci: install-and-update') &&
      !contains(github.event.pull_request.labels.*.name, 'dependencies')
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, ubuntu-latest]
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v20
      - name: Build nix-darwin configuration
        if: runner.os == 'macOS'
        run: |
          nix run nix-darwin/master#darwin-rebuild -- build --flake ./nix#macos
      - name: Build home-manager configuration
        if: runner.os == 'Linux'
        run: |
          nix build './nix#homeConfigurations."takahiko-yamashita@x86_64-linux".activationPackage'
  lint-scripts:
    runs-on: ubuntu-latest
    if: >-
      !contains(github.event.pull_request.labels.*.name, 'skip ci: install-and-update') &&
      !contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - uses: actions/checkout@v7
      - name: Check shell scripts
        shell: bash
        run: |
          shellcheck script/*.sh
          bash -n script/*.sh
  post-slack-message:
    runs-on: ubuntu-latest
    needs:
      - build-nix
      - lint-scripts
    if: failure() && contains(github.event_name, 'schedule')
    steps:
      - name: Post status
        id: slack
        uses: slackapi/slack-github-action@v3.0.3
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ vars.SLACK_CHANNEL_NAME }}
          slack-message: "failed to run install-and-update workflow"
