name: install-and-update
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  exec-install-and-update-task:
    runs-on: ${{ matrix.os }}
    if: >-
      !contains(github.event.pull_request.labels.*.name, 'skip ci: install-and-update') &&
      !contains(github.event.pull_request.labels.*.name, 'dependencies')
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Run setup.sh
        run: ./script/install.sh
      - name: Run setup task
        env:
          GIT_NAME: pyama2000
          GIT_EMAIL: example@example.com
        run: |
          cargo make --makefile script/task.toml setup \
            -e GIT_NAME="$GIT_NAME" \
            -e GIT_EMAIL="$GIT_EMAIL"
      - name: Run update task
        run: cargo make --makefile script/task.toml update
  post-slack-message:
    runs-on: ubuntu-latest
    needs:
      - exec-install-and-update-task
    if: failure() && contains(github.event_name, 'schedule')
    steps:
      - name: Post status
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ vars.SLACK_CHANNEL_NAME }}
          slack-message: "failed to run install-and-update workflow"
