name: install-and-update
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  install-and-update:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Run setup.sh
        run: ./script/install.sh
      - name: Run setup task
        env:
          GIT_NAME: pyama2000
          GIT_EMAIL: example@example.com
        run: |
          cargo make --makefile script/task.toml setup \
            -e GIT_NAME="$GIT_NAME" \
            -e GIT_EMAIL="$GIT_EMAIL"
      - name: Run update task
        run: cargo make --makefile script/task.toml update
  post-slack-message:
    runs-on: ubuntu-latest
    needs:
      - install-and-update
    if: always() && contains(github.event_name, 'schedule')
    steps:
      - name: Post status
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ vars.SLACK_CHANNEL_NAME }}
          message: "GitHub Actions install-and-update dotfiles result: ${{ needs.install-and-update.result }}"
