name: re-run
on:
  pull_request:
    branches:
      - main
    types:
      - labeled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-status:
    runs-on: ubuntu-latest
    outputs:
      check-status: ${{ steps.check.outputs.status }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: Export check workflow status
        id: check
        run: |
          gh run list --workflow check.yaml --branch "${{ github.head_ref }}" --limit 1 --json status | jq -r '.[].status'
          echo $(gh run list --workflow check.yaml --branch "${{ github.head_ref }}" --limit 1 --json status | jq -r '.[].status')
          status=$(gh run list --workflow check.yaml --branch "${{ github.head_ref }}" --limit 1 --json status | jq -r '.[].status')
          echo "status=${status}" >> "$GITHUB_OUTPUT"
  re-run:
    runs-on: ubuntu-latest
    needs:
      - check-status
    if: >-
      contains(github.event.pull_request.labels.*.name, 'skip ci: install-and-update') &&
      contains(needs.check-status.outputs.check-status, 'in_progress')
    steps:
      - name: dbg
        run: echo "${{ needs.check-status.outputs.check-status }}"
      - name: Generate GitHub Apps token
        id: generate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: add empty commit
        uses: EndBug/add-and-commit@v9
        with:
          commit: "--allow-empty"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          committer_name: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          message: "re-run"
