name: skip-ci
on:
  pull_request:
    branches:
      - main
    types:
      - labeled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  add-empty-commit:
    runs-on: ubuntu-latest
    if: >-
      contains(github.event.pull_request.labels.*.name, 'skip ci: install-and-update')
    steps:
      - run: echo ${{ toJSON(github.event.action) }}
      - name: Add re-run comment
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_URL: ${{github.event.pull_request.html_url}}
        run: gh pr comment --body '/rerun' "$PR_URL"
